version: '3.4'
services:
  localstack:
    image: localstack/localstack
    environment:
      HOSTNAME: localstack
      HOSTNAME_EXTERNAL: localstack
      SERVICES: sns,sqs
      DEFAULT_REGION: eu-west-1
      DOCKER_HOST: unix:///var/run/docker.sock

  elasticsearch:
    image: elasticsearch:7.12.1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK

  app:
    build:
      context: .
    depends_on:
      - localstack
      - elasticsearch
    command: ["cat"]
    tty: true
    volumes:
      - .:/app
    environment:
      LOG_LEVEL: warn
      AWS_ENDPOINT: http://localstack:4566
      AWS_REGION: eu-west-1
      AWS_ACCESS_KEY_ID: fake-access-key-id
      AWS_SECRET_ACCESS_KEY: fake-secret-access-key
      ELASTICSEARCH_URL: http://elasticsearch:9200
