version: '3.4'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "8080:8080"
    environment:
      HOSTNAME: localstack
      HOSTNAME_EXTERNAL: localstack
      SERVICES: sns,sqs
      DEFAULT_REGION: eu-west-1
      DOCKER_HOST: unix:///var/run/docker.sock

  app:
    build:
      context: .
    depends_on:
      - localstack
    command: ["cat"]
    tty: true
