steps:
  - label: ":bomb: Test realm-core (ruby 2.7)"
    command: docker-compose run ruby2 .buildkite/test-core.sh

  - label: ":bomb: Test realm-core (ruby 3.1)"
    command: docker-compose run ruby3 .buildkite/test-core.sh


  - label: ":bomb: Test realm-sns (ruby 2.7)"
    command: docker-compose run ruby2 .buildkite/test-sns.sh

  - label: ":bomb: Test realm-sns (ruby 3.1)"
    command: docker-compose run ruby3 .buildkite/test-sns.sh


  - label: ":bomb: Test realm-rom (ruby 2.7)"
    command: docker-compose run ruby2 .buildkite/test-rom.sh

  - label: ":bomb: Test realm-rom (ruby 3.1)"
    command: docker-compose run ruby3 .buildkite/test-rom.sh


  - label: ":bomb: Test realm-elasticsearch (ruby 2.7)"
    command: docker-compose run ruby2 .buildkite/test-elasticsearch.sh

  - label: ":bomb: Test realm-elasticsearch (ruby 3.1)"
    command: docker-compose run ruby3 .buildkite/test-elasticsearch.sh
